### ISSUE TITLE
windows folder system

### ISSUE THREAD

**Issue by SCSchmidt** [nevrome/rrtools.addin#1]
Hey,
thanks a lot for the addin, I really think it's a helpful addition to rrtools! 
It works perfectly under linux, but I've got a problem on windows: I cannot select a directory for my compendium, because there are only "linux style" directories available (starting with "home") and I'm unable to navigate to my folders. Stuck right at the beginning, I'm afraid.
Thank you for having a look! =)

**Comment by SCSchmidt** [comment]
Uh, wait, I made a screenshot:
 
![rrtools-addin-problem](https://user-images.githubusercontent.com/30059200/57639717-ce755280-75b0-11e9-8ecd-995fa9b20438.jpg)

**Comment by nevrome** [comment]
This is more tricky then I thought it would be. Would you mind testing the current version?

**Comment by SCSchmidt** [comment]
Ah cool! I now see the C partition and can do stuff there, that is great!
Buuut the drop-down menu with which I might change the partition is not reacting at all. 
![rrtools-addin-problem2019-06-03](https://user-images.githubusercontent.com/30059200/58814478-145c8e00-8626-11e9-945d-9301b2b3f5e0.jpg)
Nonetheless windows users now can use your plugin! (where is the party smiley?)

**Comment by nevrome** [comment]
So - now it should work. Please test! The partition selection works with [this](https://github.com/thomasp85/shinyFiles/issues/119#issuecomment-500180304) drop down menu.

**Comment by SCSchmidt** [comment]
Thanks! 
I now can navigate to wherever I want, but it seems to assume the path to be located on C.
So when I navigate the user interface to go to E and use folder Gegenleserei, this code is created:
```
rrtools::use_compendium(path = "/Gegenleserei/addd",rstudio = TRUE,open = TRUE)
Warning in dir.create(path) :
  cannot create dir '\Gegenleserei\addd', reason 'No such file or directory'
Warning in writeLines(c("cat(crayon::bold('\nThis project was set up by rrtools.'))",  :
  cannot open file '/Gegenleserei/addd/.Rprofile': No such file or directory
Error in writeLines(c("cat(crayon::bold('\nThis project was set up by rrtools.'))",  : 
  cannot open the connection
```
If I change the path to:
```
rrtools::use_compendium(path = "E:/Gegenleserei/addin",rstudio = TRUE,open = TRUE)
```
everything runs perfect. And if I choose a folder on C everything runs perfectly as well, even though the path is cropped:
```
rrtools::use_compendium(path = "/Users/SCSchmidt/Downloads/addin",rstudio = TRUE,open = TRUE)
```

**Comment by nevrome** [comment]
Hm. I can not reproduce this behaviour with the latest version. On my test Windows system the path construction works fine. Could you record me another .gif with this error?

**Comment by SCSchmidt** [comment]
Hey, oha, now everything works fine at my machine as well. Sorry! Maybe I had something not updated or there was an incomplete installation, but after I installed your addin anew, everything ran perfectly.
Great, thanks! :-)
