### ISSUE TITLE
Choosing a directory does not work properly (cannot browse or change drive)

### ISSUE THREAD

**Issue by homer3018** [nevrome/rrtools.addin#3]
Hello,
This might just be me, but I cannot use the directory selection functionality.
It starts and lists all the current folder of my C drive, but then upon selecting one folder (anyone), it breaks with a `Warning: Error in [: object of type 'closure' is not subsettable`. It does that whether I click on an existing folder, or the arrow if there are subfolders, or even trying to fold the C drive with its arrow.
Changing drives ends in the same fate.

Other than that, for me trying to migrate to a better and more robust workflow, I think this is a great opportunity to get get started. The way I see it I'll start slowly with this addin just to get me going with rrtools so that later on I can use rrtools directly knowing exactly what's going on.
Great piece of work there both on the addin and rrtools.
Thanks

**Comment by nevrome** [comment]
Sorry for the long delay! 

I can't reproduce the issue on my Linux machine and I have no MS Windows computer available to debug this. 

Maybe we can achieve something together. Can you run [`shinyFiles::shinyFilesExample()`](https://github.com/thomasp85/shinyFiles) and does everything work there? That's the package I use for the directory browser.

**Comment by homer3018** [comment]
I didn't mention that I have the exact same error on my Mac on which I've just confirmed that `ShinyFiles::shinyFilesExample()` works as expected! I'll test tomorrow on my windows machine to confirm I have the same behavior and report back.
Thanks !

**Comment by homer3018** [comment]
Just tested on my windows machine and `ShinyFiles::shinyFilesExample()` works as expected as well. Not too sure what's going on then, maybe a dependency thing ?

**Comment by nevrome** [comment]
Hm - ok. I just realized that `shinyFiles::shinyFilesExample()` does NOT work on my system. But for you that means that shinyFiles by it itself should work fine.

Can you run the following test app?

```
library(shiny)

ui <- basicPage(
  shinyFiles::shinyDirButton(
    id = "test_dir_select",
    label = "Choose directory",
    title = "Directory selection",
    icon = shiny::icon("folder")
  ),
  shiny::htmlOutput("test_dir_select_ready")
)

server <- function(input, output) {
  
  osSystem <- Sys.info()["sysname"]
  if (osSystem == "Linux") {
    def_roots <- c(home = "~")
  } else {
    def_roots <- shinyFiles::getVolumes()()
  }
  
  shinyFiles::shinyDirChoose(input, 'test_dir_select', roots = def_roots)  
  
  test_dir_select_ready <- shiny::reactive({
    if(length(input$test_dir_select) == 1) {
      path <- "not yet definded"
    } else {
      path <- file.path(
        shinyFiles::parseDirPath(def_roots, input$test_dir_select)
      )
    }
    return(path)
  })
  
  output$test_dir_select_ready <- shiny::renderUI({
    shiny::HTML("<font color=\"red\">", test_dir_select_ready(), "</font>")
  })
  
}

shinyApp(ui, server)

```

**Comment by homer3018** [comment]
Windows machine:
```
Warning: Error in [: object of type 'closure' is not subsettable
  [No stack trace available]
```
the app does run and get through
```
osSystem <- Sys.info()["sysname"]
  if (osSystem == "Linux") {
    def_roots <- c(home = "~")
  } else {
    def_roots <- shinyFiles::getVolumes()
  }
```
Since I can see my `C` drive and its content, but same as in the addin, I cannot browse it.

**Comment by nevrome** [comment]
I took a closer look at the shinyFiles [example code](https://github.com/thomasp85/shinyFiles/blob/master/inst/example/server.R) and realized that `shinyFiles::getVolumes()` is supposed to only return the actually relevant function. 

I adjusted the example code above accordingly. Please try!

**Comment by homer3018** [comment]
Everything now works as expected ! 👍

**Comment by nevrome** [comment]
Alright - then please also test the latest version of the rrtools.addin

**Comment by homer3018** [comment]
So I didn't test the entirety of the addin, instead just the folder selection capability which proved problematic, and it is working as expected !
Thank you very much for the assistance.

**Comment by nevrome** [comment]
Cool! So thank you for your help with testing! It's always tricky for me to reproduce Windows issues.
