### ISSUE TITLE
No help on `use_travis` error when openning addin.

### ISSUE THREAD

**Issue by eliocamp** [nevrome/rrtools.addin#4]
When I open the adding I get this error message:

```
An error has occurred!
No help on ‘use_travis’ found in RdDB ‘/home/elio/R/x86_64-pc-linux-gnu-library/4.2/rrtools/help/rrtools’
```

I think this might due to `rrtools` removing the `use_travis` function.

**Comment by nevrome** [comment]
Right - thanks. I removed the respective CI section. Maybe it comes back one day (https://github.com/benmarwick/rrtools/issues/132). The little addin should work again.
